str2int: str2int.c
	gcc -o str2int -pedantic -std=gnu99 -Wall -Werror str2int.c
dangling_pointer: dangling_pointer.c
	gcc -o dangling_pointer -pedantic -std=gnu99 -Wall -Werror dangling_pointer.c
clean:
	rm -f self_testing *.o *.c~ *.h~
